import { NextConfig } from 'next';
import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./src/config/i18n.ts');

const nextConfig: NextConfig = {
  /* config options here */
  output: 'standalone',
  eslint: {
    ignoreDuringBuilds: true,
  },
  // Explicitly expose migration env vars to client
  env: {
    // Migration configs - these need to be exposed for client-side MSW handlers
    NEXT_PUBLIC_MIGRATION_USE_API_EVENTS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_EVENTS,
    NEXT_PUBLIC_MIGRATION_USE_API_USERS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_USERS,
    NEXT_PUBLIC_MIGRATION_USE_API_ACTIONTYPES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ACTIONTYPES,
    NEXT_PUBLIC_MIGRATION_USE_API_ACTIONREFTYPES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ACTIONREFTYPES,
    NEXT_PUBLIC_MIGRATION_USE_API_ACTIONREFERENCES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ACTIONREFERENCES,
    NEXT_PUBLIC_MIGRATION_USE_API_ACTIONS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ACTIONS,
    NEXT_PUBLIC_MIGRATION_USE_API_ACTS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ACTS,
    NEXT_PUBLIC_MIGRATION_USE_API_ANOMALIES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ANOMALIES,
    NEXT_PUBLIC_MIGRATION_USE_API_CHECKLISTS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_CHECKLISTS,
    NEXT_PUBLIC_MIGRATION_USE_API_LOCOMOTIVES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_LOCOMOTIVES,
    NEXT_PUBLIC_MIGRATION_USE_API_LOCOMOTIVEMODELS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_LOCOMOTIVEMODELS,
    NEXT_PUBLIC_MIGRATION_USE_API_LOCATIONS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_LOCATIONS,
    NEXT_PUBLIC_MIGRATION_USE_API_LOCATIONLEVELS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_LOCATIONLEVELS,
    NEXT_PUBLIC_MIGRATION_USE_API_OBJECTS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_OBJECTS,
    NEXT_PUBLIC_MIGRATION_USE_API_OPERATIONTYPES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_OPERATIONTYPES,
    NEXT_PUBLIC_MIGRATION_USE_API_OPERATIONS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_OPERATIONS,
    NEXT_PUBLIC_MIGRATION_USE_API_PROCEDURES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_PROCEDURES,
    NEXT_PUBLIC_MIGRATION_USE_API_QUESTIONS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_QUESTIONS,
    NEXT_PUBLIC_MIGRATION_USE_API_RESPONSES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_RESPONSES,
    NEXT_PUBLIC_MIGRATION_USE_API_ISSUES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ISSUES,
    NEXT_PUBLIC_MIGRATION_USE_API_ASSETITEMS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ASSETITEMS,
    NEXT_PUBLIC_MIGRATION_USE_API_ASSETMODELS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ASSETMODELS,
    NEXT_PUBLIC_MIGRATION_USE_API_ENUMS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_ENUMS,
    NEXT_PUBLIC_MIGRATION_USE_API_PROFILES: process.env.NEXT_PUBLIC_MIGRATION_USE_API_PROFILES,
    NEXT_PUBLIC_MIGRATION_USE_API_SETTINGS: process.env.NEXT_PUBLIC_MIGRATION_USE_API_SETTINGS,
    NEXT_PUBLIC_MIGRATION_USE_API_AUTH: process.env.NEXT_PUBLIC_MIGRATION_USE_API_AUTH,
  },
};

export default withNextIntl(nextConfig);